### ISSUE TITLE
Is cloc giving lines or files?

### ISSUE THREAD

**Issue by Mr-Bossman** [somethingsoftware/git-stats#3]
in the code cloc is said to return lines but on the plot its files

**Comment by samiam2013** [comment]
I can't imagine these actually being confused, even with the log scale graph. but I'll check

**Comment by samiam2013** [comment]
These are not mutually exclusive, it counts both. Not an issue

**Comment by Mr-Bossman** [comment]
the size of the sphere is lines

**Comment by samiam2013** [comment]
As long as we're commenting on dead issues they're circles not spheres
