### ISSUE TITLE
Make all the GH api things in separate file

### ISSUE THREAD

**Issue by Mr-Bossman** [somethingsoftware/git-stats#5]
Make all the GH api things in separate file and put them in a class.

`run_in_dir` should also be fixed maybe editing the git command or finding a better way

**Comment by samiam2013** [comment]
there has to be a library we can use instead of doing this. Python is like the king of having libraries for things

**Comment by samiam2013** [comment]
addressed by [f0cfeec](https://github.com/somethingsoftware/git-stats/commit/f0cfeecf6b47c5fa83c640c0dd0b00ef6af1a88a)
